/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Index: typeof import('./src/components/Index.vue')['default']
    LinkButton: typeof import('./src/components/LinkButton.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WidgetsButton: typeof import('./src/components/WidgetsButton.vue')['default']
  }
}
